services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vyqour
    ports:
      - "5432:5432"
    volumes:
      - vyqour_pg:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - vyqour_redis:/data

volumes:
  vyqour_pg:
  vyqour_redis:
