import { BadRequestException } from '@nestjs/common';
import { PaymentMethod } from '@prisma/client';
import {
  mapOrderToQikinkPayload,
  toQikinkOrderNumber,
} from './qikink-order.mapper';

describe('qikink-order.mapper', () => {
  const mockUser = {
    email: 'test@example.com',
    firstName: 'John',
    lastName: 'Doe',
    phone: '9876543210',
  };

  const mockAddress = {
    id: 'addr_1',
    userId: 'user_1',
    type: 'HOME' as const,
    fullName: 'John Doe',
    phone: '9876543210',
    line1: '123 Main St',
    line2: 'Apt 4B',
    city: 'Mumbai',
    state: 'Maharashtra',
    postalCode: '400001',
    country: 'India',
    isDefault: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  };

  const baseOrder = {
    id: 'ord_123456789012',
    orderNumber: 'VYQ10001',
    userId: 'user_1',
    status: 'CONFIRMED' as const,
    paymentStatus: 'PAID' as const,
    paymentMethod: PaymentMethod.RAZORPAY,
    subtotal: 1000 as any,
    discountAmount: 0 as any,
    shippingAmount: 50 as any,
    taxAmount: 0 as any,
    total: 1050 as any,
    couponId: null,
    couponCode: null,
    shippingAddressId: 'addr_1',
    billingAddressId: null,
    notes: null,
    trackingNumber: null,
    carrier: null,
    estimatedDelivery: null,
    shippedAt: null,
    deliveredAt: null,
    cancelledAt: null,
    cancelReason: null,
    paymentId: null,
    paymentGatewayRef: null,
    invoiceUrl: null,
    qikinkOrderId: null,
    qikinkOrderNumber: null,
    qikinkStatus: null,
    qikinkSyncStatus: 'PENDING' as const,
    qikinkSyncedAt: null,
    qikinkLastError: null,
    qikinkAttempts: 0,
    qikinkPayload: null,
    qikinkResponse: null,
    qikinkAwb: null,
    qikinkCourier: null,
    qikinkShippedAt: null,
    qikinkIdempotencyKey: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    shippingAddress: mockAddress,
    user: mockUser,
  };

  describe('toQikinkOrderNumber', () => {
    it('should format order number within 15 characters', () => {
      const num = toQikinkOrderNumber({
        ...baseOrder,
        orderNumber: 'VYQ123456789012345',
      });
      expect(num.length).toBeLessThanOrEqual(15);
    });

    it('should prefer existing qikinkOrderNumber if <= 15 chars', () => {
      const num = toQikinkOrderNumber({
        ...baseOrder,
        qikinkOrderNumber: 'QIK123',
      });
      expect(num).toBe('QIK123');
    });
  });

  describe('mapOrderToQikinkPayload - Variant SKU Resolution', () => {
    it('succeeds when item has a variant and variant.qikinkSku exists', () => {
      const order = {
        ...baseOrder,
        items: [
          {
            id: 'item_1',
            orderId: 'ord_1',
            productId: 'prod_1',
            variantId: 'var_1',
            productName: 'Custom Shirt',
            variantLabel: 'M',
            sku: 'VAR-SKU-1',
            imageUrl: null,
            unitPrice: 500 as any,
            quantity: 1,
            totalPrice: 500 as any,
            product: {
              id: 'prod_1',
              name: 'Custom Shirt',
              slug: 'custom-shirt',
              description: 'Desc',
              shortDescription: null,
              basePrice: 500 as any,
              compareAtPrice: null,
              costPrice: null,
              sku: 'PROD-BASE',
              barcode: null,
              categoryId: 'cat_1',
              collectionId: null,
              status: 'ACTIVE' as const,
              isFeatured: false,
              isNewArrival: false,
              isBestSeller: false,
              isTrending: false,
              tags: [],
              materials: null,
              careInstructions: null,
              weightGrams: null,
              seoTitle: null,
              seoDescription: null,
              seoKeywords: [],
              averageRating: 0,
              reviewCount: 0,
              totalSold: 0,
              viewCount: 0,
              qikinkSku: 'PROD-QIK-SKU',
              qikinkProductId: null,
              qikinkPrintTypeId: 1,
              qikinkDesigns: [],
              qikinkSearchFromMyProducts: 1,
              qikinkSyncedAt: null,
              createdAt: new Date(),
              updatedAt: new Date(),
              publishedAt: new Date(),
              category: { slug: 't-shirts', name: 'T-Shirts' },
            },
            variant: {
              id: 'var_1',
              productId: 'prod_1',
              sku: 'VAR-SKU-1',
              size: 'M',
              color: 'Black',
              colorHex: null,
              price: 500 as any,
              compareAtPrice: null,
              stock: 10,
              lowStockAt: 5,
              imageUrl: null,
              weightGrams: null,
              isActive: true,
              qikinkSku: 'VAR-QIK-SKU-1',
              qikinkPrice: null,
              createdAt: new Date(),
              updatedAt: new Date(),
            },
          },
        ],
      };

      const payload = mapOrderToQikinkPayload(order, { shipping: '1' });
      expect(payload.line_items[0].sku).toBe('VAR-QIK-SKU-1');
    });

    it('FAILS when item has a variant without variant.qikinkSku even if product.qikinkSku exists', () => {
      const order = {
        ...baseOrder,
        items: [
          {
            id: 'item_1',
            orderId: 'ord_1',
            productId: 'prod_1',
            variantId: 'var_1',
            productName: 'Custom Shirt',
            variantLabel: 'M',
            sku: 'VAR-SKU-1',
            imageUrl: null,
            unitPrice: 500 as any,
            quantity: 1,
            totalPrice: 500 as any,
            product: {
              id: 'prod_1',
              name: 'Custom Shirt',
              slug: 'custom-shirt',
              description: 'Desc',
              shortDescription: null,
              basePrice: 500 as any,
              compareAtPrice: null,
              costPrice: null,
              sku: 'PROD-BASE',
              barcode: null,
              categoryId: 'cat_1',
              collectionId: null,
              status: 'ACTIVE' as const,
              isFeatured: false,
              isNewArrival: false,
              isBestSeller: false,
              isTrending: false,
              tags: [],
              materials: null,
              careInstructions: null,
              weightGrams: null,
              seoTitle: null,
              seoDescription: null,
              seoKeywords: [],
              averageRating: 0,
              reviewCount: 0,
              totalSold: 0,
              viewCount: 0,
              qikinkSku: 'PROD-QIK-SKU',
              qikinkProductId: null,
              qikinkPrintTypeId: 1,
              qikinkDesigns: [],
              qikinkSearchFromMyProducts: 1,
              qikinkSyncedAt: null,
              createdAt: new Date(),
              updatedAt: new Date(),
              publishedAt: new Date(),
              category: { slug: 't-shirts', name: 'T-Shirts' },
            },
            variant: {
              id: 'var_1',
              productId: 'prod_1',
              sku: 'VAR-SKU-1',
              size: 'M',
              color: 'Black',
              colorHex: null,
              price: 500 as any,
              compareAtPrice: null,
              stock: 10,
              lowStockAt: 5,
              imageUrl: null,
              weightGrams: null,
              isActive: true,
              qikinkSku: null,
              qikinkPrice: null,
              createdAt: new Date(),
              updatedAt: new Date(),
            },
          },
        ],
      };

      expect(() => mapOrderToQikinkPayload(order, { shipping: '1' })).toThrow(
        BadRequestException,
      );
    });

    it('succeeds for product-only item (no variant) with product.qikinkSku', () => {
      const order = {
        ...baseOrder,
        items: [
          {
            id: 'item_1',
            orderId: 'ord_1',
            productId: 'prod_1',
            variantId: null,
            productName: 'Custom Mug',
            variantLabel: null,
            sku: 'MUG-01',
            imageUrl: null,
            unitPrice: 300 as any,
            quantity: 1,
            totalPrice: 300 as any,
            product: {
              id: 'prod_1',
              name: 'Custom Mug',
              slug: 'custom-mug',
              description: 'Desc',
              shortDescription: null,
              basePrice: 300 as any,
              compareAtPrice: null,
              costPrice: null,
              sku: 'MUG-01',
              barcode: null,
              categoryId: 'cat_acc',
              collectionId: null,
              status: 'ACTIVE' as const,
              isFeatured: false,
              isNewArrival: false,
              isBestSeller: false,
              isTrending: false,
              tags: [],
              materials: null,
              careInstructions: null,
              weightGrams: null,
              seoTitle: null,
              seoDescription: null,
              seoKeywords: [],
              averageRating: 0,
              reviewCount: 0,
              totalSold: 0,
              viewCount: 0,
              qikinkSku: 'PROD-QIK-MUG',
              qikinkProductId: null,
              qikinkPrintTypeId: 1,
              qikinkDesigns: [],
              qikinkSearchFromMyProducts: 1,
              qikinkSyncedAt: null,
              createdAt: new Date(),
              updatedAt: new Date(),
              publishedAt: new Date(),
              category: { slug: 'accessories', name: 'Accessories' },
            },
            variant: null,
          },
        ],
      };

      const payload = mapOrderToQikinkPayload(order, { shipping: '1' });
      expect(payload.line_items[0].sku).toBe('PROD-QIK-MUG');
    });

    it('FAILS for product-only item (no variant) without product.qikinkSku', () => {
      const order = {
        ...baseOrder,
        items: [
          {
            id: 'item_1',
            orderId: 'ord_1',
            productId: 'prod_1',
            variantId: null,
            productName: 'Custom Mug',
            variantLabel: null,
            sku: 'MUG-01',
            imageUrl: null,
            unitPrice: 300 as any,
            quantity: 1,
            totalPrice: 300 as any,
            product: {
              id: 'prod_1',
              name: 'Custom Mug',
              slug: 'custom-mug',
              description: 'Desc',
              shortDescription: null,
              basePrice: 300 as any,
              compareAtPrice: null,
              costPrice: null,
              sku: 'MUG-01',
              barcode: null,
              categoryId: 'cat_acc',
              collectionId: null,
              status: 'ACTIVE' as const,
              isFeatured: false,
              isNewArrival: false,
              isBestSeller: false,
              isTrending: false,
              tags: [],
              materials: null,
              careInstructions: null,
              weightGrams: null,
              seoTitle: null,
              seoDescription: null,
              seoKeywords: [],
              averageRating: 0,
              reviewCount: 0,
              totalSold: 0,
              viewCount: 0,
              qikinkSku: null,
              qikinkProductId: null,
              qikinkPrintTypeId: 1,
              qikinkDesigns: [],
              qikinkSearchFromMyProducts: 1,
              qikinkSyncedAt: null,
              createdAt: new Date(),
              updatedAt: new Date(),
              publishedAt: new Date(),
              category: { slug: 'accessories', name: 'Accessories' },
            },
            variant: null,
          },
        ],
      };

      expect(() => mapOrderToQikinkPayload(order, { shipping: '1' })).toThrow(
        BadRequestException,
      );
    });
  });
});
